name: sunday_school_attendance
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  get:
  google_fonts: ^6.2.1
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  intl: ^0.20.2
  flutter_time_picker_spinner: ^2.0.0
  http: ^1.3.0
  http_parser: ^4.1.2
  cloudinary_url_gen: ^1.7.0
  cloudinary_flutter: ^1.3.0
  flutter_dotenv: ^5.2.1
  file_picker: ^9.1.0
  firebase_auth: ^5.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
