platform :ios, '13.0'

target 'Runner' do
  use_frameworks!
  
  # Firebase dependencies
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Force Swift version to avoid compiler errors with some Firebase pods
      config.build_settings['SWIFT_VERSION'] = '5.8'
    end
  end
end

