platform :ios, '13.0'

target 'Runner' do
  use_frameworks!

  pod 'Firebase/Core', '10.11.0'
  pod 'Firebase/Firestore', '10.11.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5.8'
    end
  end
end

