name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - run: flutter pub get
      
      - run: flutter clean
      
      # Clean old pods & Flutter.framework
      - run: rm -rf ios/Pods ios/Podfile.lock ios/Flutter/Flutter.framework
      
      # Update CocoaPods repo and cache, inside ios folder
      - run: |
          sudo gem install cocoapods --pre
          pod cache clean --all
          pod repo update
          pod install
        working-directory: ios

      # Build ios app without codesigning
      - run: flutter build ios --release --no-codesign

      # Prepare Payload folder for IPA
      - run: mkdir Payload
        working-directory: build/ios/iphoneos

      - run: mv Runner.app/ Payload
        working-directory: build/ios/iphoneos

      # Zip to .ipa
      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      # Upload to release
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is first release"

